function drawCasts(t){drawCastBar(EXDEATH_POS,'Black Hole',13.7,16.5,t,'#8066e8');drawCastBar(EXDEATH_POS,'Thunder III',29.1,33.8,t,'#9064ff');drawCastBar(CHAOS_POS,'Damning Edict',37.3,42.5,t,'#e5673e');drawCastBar(CHAOS_POS,'Damning Edict',64.7,69.8,t,'#e5673e');drawCastBar(EXDEATH_POS,'Thunder III',70.4,75.1,t,'#9064ff');drawCastBar(CHAOS_POS,state.latSidesFirst?'Latitudinal Implosion':'Longitudinal Implosion',105.3,110.7,t,'#7a61db');drawCastBar(EXDEATH_POS,'White Hole',105.3,110.7,t,'#d9d5ff')}
function drawBot(s,b,t){const g=project(b.x,b.z),sc=g.s*.86,ass=state.party.bySlot[s];ellipse(g.x,g.y+7*sc,13*sc,4*sc,'rgba(0,0,0,.45)');ctx.save();ctx.translate(g.x,g.y-14*sc);ctx.scale(sc,sc);ctx.fillStyle=isDps(s)?'#8b5577':'#607b9b';ctx.strokeStyle='#ddd';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(0,-12,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillRect(-6,-6,12,24);ctx.restore();text(s,g.x,g.y-49*sc,10*sc,'#eaf2ff');circle(g.x+16*sc,g.y-40*sc,8*sc,ass.line===1?'#617bff':ass.line===2?'#b07aff':'#e0aa57','#fff',1);text(ass.line,g.x+16*sc,g.y-40*sc,8*sc);if((t<7||state.hints)&&ass.acc){circle(g.x-16*sc,g.y-40*sc,7*sc,'#b85ec8','#fff',1);text('A',g.x-16*sc,g.y-40*sc,7*sc)}}
function drawPlayer(){const x=W/2,y=H*.79,now=performance.now(),moving=Math.hypot(state.joyX,state.joyY)>.12||[...state.keys].some(k=>['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)),stride=moving?Math.sin(now/95)*7:0,bob=moving?Math.abs(Math.sin(now/95))*3:Math.sin(now/420)*1.1;ellipse(x,y+18,45,13,'rgba(0,0,0,.52)');ctx.save();ctx.translate(x,y-20+bob);ctx.scale(1.58,1.58);ctx.strokeStyle='#d5d2db';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(10,18);ctx.quadraticCurveTo(42,25,36,49);ctx.stroke();ctx.strokeStyle='#2b2940';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-7,28);ctx.lineTo(-10-stride*.45,48);ctx.moveTo(7,28);ctx.lineTo(10+stride*.45,48);ctx.stroke();ctx.fillStyle='#eee9df';ctx.strokeStyle='#aaa4b0';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(0,-34);ctx.quadraticCurveTo(-23,-18,-27,34);ctx.lineTo(-17,49);ctx.lineTo(-4,39);ctx.lineTo(0,53);ctx.lineTo(6,39);ctx.lineTo(18,49);ctx.lineTo(28,34);ctx.quadraticCurveTo(23,-18,0,-34);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#574d7c';ctx.fillRect(-18,-7,11,48);ctx.fillRect(7,-7,11,48);circle(0,-46,11,'#ddb89c','#2a2932',1.5);ctx.fillStyle='#d8d5df';ctx.beginPath();ctx.moveTo(-9,-54);ctx.lineTo(-15,-70);ctx.lineTo(-2,-58);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(9,-54);ctx.lineTo(15,-70);ctx.lineTo(2,-58);ctx.closePath();ctx.fill();ctx.strokeStyle='#c7aa5d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(27,-18);ctx.lineTo(34,52);ctx.stroke();circle(25,-25,8,'#7667e8','#ece9ff',1.6);ctx.restore();text(roleSelect.value,x,y-142,15,'#baffcf')}
function drawTethers(t){for(const w of getActiveWaves(t)){const maps=waveAssignments(w),ws=state.waveState[w.id];for(const a of maps){const src=sourcePos(w.set,a.source),sg=project(src.x,src.z,4);let tar;if(a.slot===roleSelect.value){if(ws.grabbed)tar={x:W/2,y:H*.79-30};else{const b=state.bots[ws.holder];if(!b)continue;const q=project(b.x,b.z,10);tar={x:q.x,y:q.y}}}else{const b=state.bots[a.slot];if(!b)continue;const q=project(b.x,b.z,10);tar={x:q.x,y:q.y}}line([sg,tar],a.slot===roleSelect.value&&ws.grabbed?'#78f6e0':'#10131d',a.slot===roleSelect.value&&ws.grabbed?3.4:3,.88);line([sg,tar],'rgba(157,232,255,.5)',1.1,.7)}if(state.hints){const mine=maps.find(a=>a.slot===roleSelect.value);if(mine){const p=ws.grabbed?baitPos(w.set,mine.source):prePos(w.set,mine.source);groundCircle(p.x,p.z,11,'rgba(255,224,132,.08)','#ffe084',2,.95)}}}}
function drawLasers(t){state.lasers=state.lasers.filter(l=>t<=l.end);for(const l of state.lasers){const a=project(l.source.x,l.source.z,3);let dx=l.target.x-l.source.x,dz=l.target.z-l.source.z,L=Math.hypot(dx,dz)||1;dx/=L;dz/=L;const e=project(l.source.x+dx*190,l.source.z+dz*190,3);line([a,e],'#4d74ff',13,.28);line([a,e],'#b8ccff',3,.95)}}
function drawArenaEntities(t){for(const w of WAY)drawWay(w[0],w[1]);const set=currentBHSet(t);if(set)for(const h of bhPositions(set))drawBlackHole(h,t);drawDamning(t);drawLat(t);drawSlap(t);drawBodySlam(t);drawBoss(CHAOS_POS,'CHAOS','chaos');drawBoss(EXDEATH_POS,'EXDEATH','exdeath');if(t>=6.5)drawKefka(t);const botArr=Object.values(state.bots).sort((a,b)=>project(a.x,a.z).d-project(b.x,b.z).d);botArr.forEach(b=>drawBot(b.slot,b,t));drawTethers(t);drawLasers(t);drawCasts(t);drawPlayer()}
function drawIdle(){drawFloor();WAY.forEach(w=>drawWay(w[0],w[1]));drawBoss(CHAOS_POS,'CHAOS','chaos');drawBoss(EXDEATH_POS,'EXDEATH','exdeath');drawPlayer()}
function draw(now){ctx.clearRect(0,0,W,H);drawFloor();if(state.party)drawArenaEntities(state.t);else{WAY.forEach(w=>drawWay(w[0],w[1]));drawBoss(CHAOS_POS,'CHAOS','chaos');drawBoss(EXDEATH_POS,'EXDEATH','exdeath');drawPlayer()}const v=ctx.createRadialGradient(W/2,H*.52,H*.18,W/2,H*.52,W*.72);v.addColorStop(.5,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.3)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function frame(now){const dt=Math.min(.04,(now-state.last)/1000);state.last=now;update(dt,now);draw(now);requestAnimationFrame(frame)}

function stick(el,e){const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.36),y=(e.clientY-cy)/(r.height*.36),m=Math.hypot(x,y);if(m>1){x/=m;y/=m}return{x,y,r}}
function bindStick(el,type){el.addEventListener('pointerdown',e=>{e.stopPropagation();const s=stick(el,e);if(type==='move'){state.movePid=e.pointerId;state.joyX=s.x;state.joyY=s.y}else{state.camPid=e.pointerId;state.camX=s.x}el.setPointerCapture(e.pointerId);el.style.setProperty('--jx',s.x*s.r.width*.24+'px');el.style.setProperty('--jy',s.y*s.r.height*.24+'px');e.preventDefault()});el.addEventListener('pointermove',e=>{const id=type==='move'?state.movePid:state.camPid;if(e.pointerId!==id)return;const s=stick(el,e);if(type==='move'){state.joyX=s.x;state.joyY=s.y}else state.camX=s.x;el.style.setProperty('--jx',s.x*s.r.width*.24+'px');el.style.setProperty('--jy',s.y*s.r.height*.24+'px');e.preventDefault()});const up=e=>{if(type==='move'&&e.pointerId===state.movePid){state.movePid=null;state.joyX=state.joyY=0}else if(type==='cam'&&e.pointerId===state.camPid){state.camPid=null;state.camX=0}else return;el.style.setProperty('--jx','0px');el.style.setProperty('--jy','0px')};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)}
bindStick(joy,'move');bindStick(camJoy,'cam');
sprintBtn.addEventListener('pointerdown',e=>{e.stopPropagation();const now=performance.now();if(now>=state.sprintUntil){state.sprintUntil=now+2600;sprintBtn.classList.add('on');setTimeout(()=>sprintBtn.classList.remove('on'),2650)}e.preventDefault()});
startBtn.addEventListener('click',setupRun);modeSelect.addEventListener('change',syncMode);roleSelect.addEventListener('change',()=>{if(TANKS.includes(roleSelect.value)&&accSelect.value==='yes')accSelect.value='no';syncMode()});lineSelect.addEventListener('change',()=>{if(+lineSelect.value===3&&accSelect.value==='yes')accSelect.value='no';syncMode()});accSelect.addEventListener('change',()=>{if((TANKS.includes(roleSelect.value)||+lineSelect.value===3)&&accSelect.value==='yes')accSelect.value='no';syncMode()});hintBtn.addEventListener('click',()=>{state.hints=!state.hints;hintBtn.textContent=state.hints?'Hints ON':'Hints OFF';hintBtn.setAttribute('aria-pressed',state.hints)});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowleft','arrowright','arrowup','arrowdown'].includes(k)){state.keys.add(k);e.preventDefault()}if(k==='q')rotateCamera(-.18);if(k==='e')rotateCamera(.18);if((k==='r'||k==='enter'||k===' ')&&!e.repeat){setupRun();e.preventDefault()}},{passive:false});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
syncMode();requestAnimationFrame(frame);
