function stick(el,e){const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.36),y=(e.clientY-cy)/(r.height*.36),m=Math.hypot(x,y);if(m>1){x/=m;y/=m}return{x,y,r}}
function bindStick(el,type){el.addEventListener('pointerdown',e=>{e.stopPropagation();const s=stick(el,e);if(type==='move'){state.movePid=e.pointerId;state.joyX=s.x;state.joyY=s.y}else{state.camPid=e.pointerId;state.camX=s.x}el.setPointerCapture(e.pointerId);el.style.setProperty('--jx',s.x*s.r.width*.24+'px');el.style.setProperty('--jy',s.y*s.r.height*.24+'px');e.preventDefault()});el.addEventListener('pointermove',e=>{const id=type==='move'?state.movePid:state.camPid;if(e.pointerId!==id)return;const s=stick(el,e);if(type==='move'){state.joyX=s.x;state.joyY=s.y}else state.camX=s.x;el.style.setProperty('--jx',s.x*s.r.width*.24+'px');el.style.setProperty('--jy',s.y*s.r.height*.24+'px');e.preventDefault()});const up=e=>{if(type==='move'&&e.pointerId===state.movePid){state.movePid=null;state.joyX=state.joyY=0}else if(type==='cam'&&e.pointerId===state.camPid){state.camPid=null;state.camX=0}else return;el.style.setProperty('--jx','0px');el.style.setProperty('--jy','0px')};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)}
bindStick(joy,'move');bindStick(camJoy,'cam');
sprintBtn.addEventListener('pointerdown',e=>{e.stopPropagation();const n=performance.now();if(n>=state.sprintUntil){state.sprintUntil=n+2600;sprintBtn.classList.add('on');setTimeout(()=>sprintBtn.classList.remove('on'),2650)}e.preventDefault()});
hintBtn.addEventListener('click',()=>{state.hints=!state.hints;hintBtn.textContent=state.hints?'Hints ON':'Hints OFF';hintBtn.setAttribute('aria-pressed',state.hints)});
startBtn.addEventListener('click',startRun);
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowleft','arrowright','arrowup','arrowdown'].includes(k)){state.keys.add(k);e.preventDefault()}if(k==='q')rotateCamera(.18);if(k==='e')rotateCamera(-.18);if((k==='r'||k==='enter'||k===' ')&&!e.repeat){startRun();e.preventDefault()}},{passive:false});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
function frame(now){const dt=Math.min(.04,(now-state.last)/1000);state.last=now;update(dt,now);draw();requestAnimationFrame(frame)}
syncControls();youHud.textContent=roleSelect.value;draw();requestAnimationFrame(frame);
