function projectRelative(x,z){const dx=x-state.player.x,dz=z-state.player.z,ca=Math.cos(state.cam),sa=Math.sin(state.cam);return{right:ca*dx-sa*dz,forward:-sa*dx-ca*dz}}
function project(x,z,h=0){const c=projectRelative(x,z),pers=clamp(1/(1+c.forward/210),.46,2.15);return{x:W/2+c.right*5.55*pers,y:H*.79-c.forward*3.8*pers-h*1.42*pers,s:pers,d:c.forward}}
function circle(x,y,r,fill,stroke=null,w=1,a=1){ctx.save();ctx.globalAlpha=a;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=w;ctx.stroke()}ctx.restore()}
function ellipse(x,y,rx,ry,fill,a=1){ctx.save();ctx.globalAlpha=a;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.restore()}
function poly(ps,fill,stroke=null,w=1,a=1){if(ps.length<3)return;ctx.save();ctx.globalAlpha=a;ctx.beginPath();ctx.moveTo(ps[0].x,ps[0].y);for(let i=1;i<ps.length;i++)ctx.lineTo(ps[i].x,ps[i].y);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=w;ctx.stroke()}ctx.restore()}
function line(ps,color,w=1,a=1){ctx.save();ctx.globalAlpha=a;ctx.strokeStyle=color;ctx.lineWidth=w;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();ctx.moveTo(ps[0].x,ps[0].y);for(let i=1;i<ps.length;i++)ctx.lineTo(ps[i].x,ps[i].y);ctx.stroke();ctx.restore()}
function text(t,x,y,size,color='#fff',weight='800',align='center'){ctx.save();ctx.fillStyle=color;ctx.font=`${weight} ${size}px system-ui`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=4;ctx.fillText(t,x,y);ctx.restore()}
function groundCircle(x,z,r,fill,stroke=null,w=1,a=1){const ps=[];for(let i=0;i<48;i++){const a=i/48*Math.PI*2;ps.push(project(x+Math.cos(a)*r,z+Math.sin(a)*r))}poly(ps,fill,stroke,w,a)}
function groundLineThrough(angle,width,color,a=1){const d=rad(angle),ux=Math.sin(d),uz=-Math.cos(d),vx=Math.cos(d),vz=Math.sin(d),L=112,w=width/2;const ps=[project(-ux*L+vx*w,-uz*L+vz*w),project(ux*L+vx*w,uz*L+vz*w),project(ux*L-vx*w,uz*L-vz*w),project(-ux*L-vx*w,-uz*L-vz*w)];poly(ps,color,null,0,a)}
function wedge(cx,cz,facing,halfAngle,r,fill,a=.55){const ps=[project(cx,cz)];for(let i=0;i<=30;i++){const d=facing-halfAngle+(2*halfAngle*i/30),p=rotate({x:0,z:-r},d);ps.push(project(cx+p.x,cz+p.z))}poly(ps,fill,null,0,a)}
function drawFloor(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#697089');g.addColorStop(.27,'#3f4863');g.addColorStop(.52,'#20273a');g.addColorStop(1,'#090c13');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<56;i++){const a=i/56*Math.PI*2,p0=project(0,0),p1=project(Math.cos(a)*ARENA_R,Math.sin(a)*ARENA_R),p2=project(Math.cos(a+Math.PI*2/56)*ARENA_R,Math.sin(a+Math.PI*2/56)*ARENA_R);poly([p0,p1,p2],i%2?'#18223a':'#202a45')}for(const rr of [18,36,54,72,90,99]){const ps=[];for(let i=0;i<=100;i++){const a=i/100*Math.PI*2;ps.push(project(Math.cos(a)*rr,Math.sin(a)*rr))}line(ps,rr===99?'#86b2c8':'#344863',rr===99?4:1.2,rr===99?.95:.7)}for(let i=0;i<24;i++){const a=i/24*Math.PI*2;line([project(Math.cos(a)*7,Math.sin(a)*7),project(Math.cos(a)*98,Math.sin(a)*98)],i%3===0?'#4d6684':'#273851',i%3===0?1.5:.7,.58)}}
function drawBoss(name,p,color,scale=1){const q=project(p.x,p.z),s=q.s*scale;ellipse(q.x,q.y+8*s,25*s,7*s,'rgba(0,0,0,.42)');ctx.save();ctx.translate(q.x,q.y-12*s);ctx.scale(s,s);ctx.fillStyle=color;ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(0,-38);ctx.quadraticCurveTo(-24,-20,-22,28);ctx.lineTo(-10,36);ctx.lineTo(0,25);ctx.lineTo(10,36);ctx.lineTo(22,28);ctx.quadraticCurveTo(24,-20,0,-38);ctx.closePath();ctx.fill();ctx.stroke();circle(0,-47,8,'#edc8ad');ctx.restore();text(name,q.x,q.y-72*s,12*s,'#f4e8ff')}
function drawKefka(){const angle=state.kefka.facingFactor*45,outer=rotate({x:0,z:-112},angle);let p=outer;if(state.kefka.leaping){const pulse=(Math.sin(state.elapsed*12)+1)/2;p={x:outer.x*(.25+.75*pulse),z:outer.z*(.25+.75*pulse)}}drawBoss('GIANT KEFKA',p,'#763f91',1.35);if(state.hints){const q=project(outer.x*.74,outer.z*.74);text('REL N',q.x,q.y-20,12,'#8fe9ff')}}
function drawCharacter(role,p,isPlayer=false){const q=isPlayer?{x:W/2,y:H*.79,s:1.55}:project(p.x,p.z),s=q.s*(isPlayer?1:1);ellipse(q.x,q.y+9*s,13*s,4*s,'rgba(0,0,0,.45)');ctx.save();ctx.translate(q.x,q.y-11*s);ctx.scale(s,s);ctx.fillStyle=isPlayer?'#eee9df':'#8196dc';ctx.strokeStyle=isPlayer?'#bfa8ff':'#d3dcff';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,-20);ctx.quadraticCurveTo(-11,-8,-10,16);ctx.lineTo(-5,24);ctx.lineTo(0,18);ctx.lineTo(5,24);ctx.lineTo(10,16);ctx.quadraticCurveTo(11,-8,0,-20);ctx.closePath();ctx.fill();ctx.stroke();circle(0,-26,5,isPlayer?'#ddb89c':'#c8b5a8');ctx.restore();text(DISPLAY[role],q.x,q.y-46*s,10*s,isPlayer?'#a9ffc9':'#cbd7ff')}
function drawBlackholes(){if(!state.activeBH)return;const sorted=[...state.activeBH.holes].sort((a,b)=>project(b.x,b.z).d-project(a.x,a.z).d);for(const h of sorted){const q=project(h.x,h.z),s=q.s,pulse=1+Math.sin(state.elapsed*4+h.x*.02)*.08,gr=ctx.createRadialGradient(q.x,q.y,1,q.x,q.y,15*s);gr.addColorStop(0,'#000');gr.addColorStop(.46,'#020309');gr.addColorStop(.63,'#3e3b69');gr.addColorStop(.76,'#9be8ff');gr.addColorStop(1,'rgba(40,50,90,0)');circle(q.x,q.y,15*s*pulse,gr,null,0,.95);circle(q.x,q.y,7*s,'#020206','#d6f8ff',1*s,.75)}}
function drawTethers(){if(!state.activeBH)return;for(const t of state.activeTethers){if(t.hit)continue;const src=project(t.src.x,t.src.z,2),target=t.role===state.playerRole?project(state.player.x,state.player.z,8):project(state.bots[t.role].x,state.bots[t.role].z,8);line([src,target],t.role===state.playerRole?'#f6ecff':'#c1c9e8',t.role===state.playerRole?3.2:2.1,.82);circle(src.x,src.y,4*src.s,'#08090d','#fff',1.2,.95)}}
function drawLasers(){for(const l of state.laserFx){const s=project(l.src.x,l.src.z),t=project(l.target.x,l.target.z),dx=t.x-s.x,dy=t.y-s.y,m=Math.hypot(dx,dy)||1,ex=t.x+dx/m*240,ey=t.y+dy/m*240;line([s,{x:ex,y:ey}],'#234cff',15,.63);line([s,{x:ex,y:ey}],'#a8c9ff',4,.9)}}
function drawSlap(){if(!state.slap)return;const safe=state.slap.safe,danger=safe==='LEFT'?'RIGHT':'LEFT',sign=danger==='RIGHT'?1:-1,positions=[{x:sign*50,z:-50},{x:sign*50,z:0},{x:sign*50,z:50}];if(state.slap.phase.startsWith('hit')){const n=+state.slap.phase.slice(3)-1;groundCircle(positions[n].x,positions[n].z,33,'rgba(200,215,255,.38)','#dce6ff',2,.8)}if(state.slap.phase==='center'){groundCircle(0,0,23,'rgba(209,188,255,.55)','#efe7ff',2,.9);if(safe==='RIGHT'){wedge(0,0,90,40,105,'rgba(119,83,201,.58)',.7)}else{wedge(0,0,210,38,105,'rgba(119,83,201,.55)',.7);wedge(0,0,270,38,105,'rgba(119,83,201,.55)',.7);wedge(0,0,330,38,105,'rgba(119,83,201,.55)',.7)}}const hand=project(sign*88,0,15);text(safe==='RIGHT'?'RIGHT SAFE · PARTY STACK':'LEFT SAFE · ROLE STACK',W/2,H*.17,18,'#ffe6a0');text('✋',hand.x,hand.y,32,'#fff')}
function drawAoEs(){for(const a of state.aoes){if(a.type==='edict')wedge(0,0,a.facing,89.5,118,'rgba(255,67,48,.58)',.74);if(a.type==='latlong'&&a.mode==='first'){wedge(0,0,a.facing+90,63.75,118,'rgba(159,105,231,.55)',.72);wedge(0,0,a.facing-90,63.75,118,'rgba(159,105,231,.55)',.72)}if(a.type==='bodyslamTele')groundLineThrough(a.angle,35,'rgba(255,155,74,.34)',.8);if(a.type==='bodyslam')groundLineThrough(a.angle,35,'rgba(255,76,48,.70)',.92)}}
function drawCasts(){const c=state.casts[state.casts.length-1];if(!c)return;const p=clamp((state.elapsed-c.start)/(c.end-c.start),0,1),w=430,x=W/2-w/2,y=H-28;ctx.fillStyle='rgba(9,11,17,.85)';ctx.fillRect(x-7,y-18,w+14,32);ctx.fillStyle='#2a3044';ctx.fillRect(x,y,w,9);ctx.fillStyle='#d78b61';ctx.fillRect(x,y,w*p,9);text(c.label,W/2,y-9,11)}
function drawHUDOverlay(){if(state.activeBH)text(`BLACK HOLE SET ${state.activeBH.block} · WAVE ${state.activeBH.wave}`,W/2,52,13,'#dffaff');if(state.phase==='result')text(state.mistakes===0?'CLEAN RUN':'RUN COMPLETE',W/2,H*.34,31,state.mistakes===0?'#a6ffd0':'#ffe0a0')}
function draw(){ctx.clearRect(0,0,W,H);drawFloor();drawAoEs();drawBlackholes();drawBoss('CHAOS',state.chaos,'#b44573',1.1);drawBoss('EXDEATH',state.exdeath,'#6a75b7',.95);drawKefka();for(const [r,b] of Object.entries(state.bots))drawCharacter(r,b,false);drawTethers();drawLasers();drawSlap();drawCharacter(state.playerRole,state.player,true);drawCasts();drawHUDOverlay();const v=ctx.createRadialGradient(W/2,H*.5,H*.25,W/2,H*.5,W*.7);v.addColorStop(.55,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.28)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
